### ISSUE TITLE
Backend to-do list

### ISSUE THREAD

**Issue by richjpex** [richjpex/CCAPDEV-Cafebara-GROUP11#68]
- [ ] Search establishments/reviews
- [ ] Mark helpful/unhelpful
- [ ] Include search bar in "View Cafes" page
- [ ] Sorting cafes by 1,2,3,4,5 capybaras
- [ ] Edit and delete review
- [ ] Suggestion from sir: remove bio and profile picture from register, have the user to set them only from their profile view
- [ ] What should the map sa "View Cafes" page do?
- [ ] Fix database

@nemurinoU @miiiigs @BanzaiNamco
